# Some overall notes on how this works
#
# * We smoke using the system provided latest, and custom built "oddball perls"
# The reason for not having a blanket matrix is to conserve travis resources
# as a full DBIC depchain isn't cheap
#
# * Minimum perl officially supported by DBIC is 5.8.3. This *includes* the
# basic depchain. On failure either attempt to fix it or bring it to the
# attention of ribasushi. *DO NOT* disable 5.8 testing - it is here for a
# reason
#
# * The matrix is built from two main modes - CLEANTEST = [true|false].
# - In the first case we test with minimal deps available, and skip everything
#   listed in DBIC::OptDesps. The modules are installed with classic CPAN
#   invocations and are *fully tested*. In other words we simulate what would
#   happen if a user tried to install on a just-compiled virgin perl
# - Without CLEANTEST we bring the armada of RDBMS and install the maximum
#   possible set of deps *without testing them*. This ensures we stay within
#   a reasonable build-time and still run as many of our tests as possible
#
# * The perl builds and the DBIC tests run under NUMTHREADS number of threads.
# The testing of dependencies under CLEANTEST runs single-threaded, at least
# until we fix our entire dep-chain to safely pass under -j
#
# * The way .travis.yml is fed to the command controller is idiotic - it
# makes using multiline `bash -c` statements impossible. Therefore to
# aid readability (our travis logic is rather complex), the bulk of
# functionality is moved to scripts. More about the problem (and the
# WONTFIX "explanation") here: https://github.com/travis-ci/travis-ci/issues/497
#
# the entire run times out after 50 minutes, or after 5 minutes without
# console output

#
# Smoke all branches except for blocked* and wip/*
#
# Additionally master does not smoke with bleadperl
# ( implemented in maint/travis-ci_scripts/10_before_install.bash )
#
branches:
  except:
    - /^wip\//
    - /^blocked/

notifications:
  irc:
    channels:
      - "irc.perl.org#dbic-smoke"
    template:
      - "%{branch}#%{build_number} by %{author}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
    use_notice: true

  email:
    recipients:
      - ribasushi@cpan.org
      # Temporary - if it proves to be too noisy, we'll shut it off
      #- dbix-class-devel@lists.scsys.co.uk
    on_success: change
    on_failure: always

# FIXME - This stuff is not yet available for free OSS accounts, sadpanda
# First paragrah on http://about.travis-ci.org/docs/user/caching/
#cache:
#  apt: true
#  directories:
#    - /var/cache/apt/archives

language: perl

perl:
  - "5.8"
  - "5.20-extras"
  - "5.20"
  - "5.18-extras"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

env:
  - CLEANTEST=false
  - CLEANTEST=true

###
### For the following two phases -e is *set*
###

before_install:
  # common functions for all run phases below
  #
  # this is an exporter - sourcing it is crucial
  # among other things it also sets -e
  #
  - source maint/travis-ci_scripts/common.bash

  # Sets global envvars, downloads/configures debs based on CLEANTEST
  # Sets extra DBICTEST_* envvars
  #
  # this is an exporter - sourcing it is crucial
  #
  - source maint/travis-ci_scripts/10_before_install.bash

install:
  # Build and switch to a custom perl if requested
  # Configure the perl env, preinstall some generic toolchain parts
  # Possibly poison the environment
  #
  # this is an exporter - sourcing it is crucial
  #
  - source maint/travis-ci_scripts/20_install.bash

###
### From this point on -e is *unset*, rely on travis' error handling
###
  - set +e

before_script:
  # Preinstall/install deps based on envvars/CLEANTEST
  #
  # need to invoke the after_failure script manually
  # because 'after_failure' runs only after 'script' fails
  #
  - maint/getstatus maint/travis-ci_scripts/30_before_script.bash || ( maint/travis-ci_scripts/50_after_failure.bash && /bin/false )

script:
  # Run actual tests
  #
  - maint/getstatus maint/travis-ci_scripts/40_script.bash

after_success:
  # Check if we can assemble a dist properly if not in CLEANTEST
  #
  - maint/getstatus maint/travis-ci_scripts/50_after_success.bash

after_failure:
  # Final sysinfo printout on fail
  #
  - maint/getstatus maint/travis-ci_scripts/50_after_failure.bash

after_script:
  # No tasks yet
  #
  #- maint/getstatus maint/travis-ci_scripts/60_after_script.bash
